Add SecretText overload
microsoft/BCApps pull request #413
Opened 2023-12-06 13:05 UTC by SBalslev

When working with Azure KeyVault it should be possible to get secrets as SecretText.

Fixes AB#493425

2023-12-06 15:08 UTC, pri-kise commented
I like this PR, but those methods are all Scope OnPrem.

What could be very useful is to add such methods to a `interface "Secret Provider V2"` and implement this in `codeunit 3800 "App Key Vault Secret Provider"`.
Are there already plans to improve those codeunits, too?

See also : https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-app-key-vault

2023-12-07 15:22 UTC, darjoo commented
We should obsolete the old function and move towards recommending using only the SecretText function.

2023-12-08 14:29 UTC, SBalslev commented
> We should obsolete the old function and move towards recommending using only the SecretText function.

At this point I disagree; we do not know the data stored in KeyVault so we cannot make assumptions that all consumers will use the data in a context that can use SecretText. An example is configuration data like Microsoft Entra application client id.

2023-12-12 08:04 UTC, christianbraeunlich requested changes

2023-12-12 08:04 UTC, christianbraeunlich commented on src/System Application/App/Secrets/src/AppKeyVaultSecretPrImpl.Codeunit.al
> +        if not GetSecret(SecretName, secretValueText) then
```suggestion
        if not GetSecret(SecretName, SecretValueText) then
```

2023-12-12 08:04 UTC, christianbraeunlich commented on src/System Application/App/Secrets/src/InMemorySecretProvImpl.Codeunit.al
> +        if not GetSecret(SecretName, secretValueText) then
```suggestion
        if not GetSecret(SecretName, SecretValueText) then
```

2024-01-17 14:15 UTC, darjoo commented on src/System Application/App/Secrets/src/SecretProviderv2.Interface.al
> +interface "Secret Provider v2"
Last bit, missing tests

2024-01-18 11:32 UTC, JesperSchulz approved these changes

2024-01-18 11:50 UTC, BazookaMusic approved these changes
Looks good

2024-01-18 12:38 UTC, merged